name: dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: <your name> <email@example.com>
#homepage: https://www.example.com
#dependencies:
#  lib_name: any
dev_dependencies:
  test: '>=0.12.0'
