name: open_location_code
description: Plus Codes are short, generated codes that can be used like street addresses, for places where street addresses don't exist.
version: 0.0.1
homepage: https://maps.google.com/pluscodes/
environment:
  sdk: '^2.19.6'
dev_dependencies:
  test: ^1.24.3
